### **Week 7, Challenge (Optional)**

---

#### Conway's Game of Life

Using Numpy, let's simulate the Conway's Game of Life. (See https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life for the history and detailed descriptions.)

![GoLUrl](https://upload.wikimedia.org/wikipedia/commons/e/e5/Gospers_glider_gun.gif "Game of Life")

Game of Life is a simulation of a system called *Cellular Automata*. You simply initialize the dots in a two-dimensional world and apply rules to obtain the next state. Over time, you will observe some moving patterns. An example is shown above.

The rules of the Life is shown below. At each time point:

- Any live cell with two or three live neighbors survives. (Neighbors: 8 cells aroun the cell)

- Any dead cell with three live neighbors becomes a live cell.

- All other live cells die in the next generation. Similarly, all other dead cells stay dead.


Try implement it.

1. Initialize a matrix with random 0's and 1's. Then you need another matrix to store a future world.

2. Write a for-loop with some iterations.

3. Inside the for-loop, update each cell, based on the three rules described above.
    
4. Plot it and wait 0.2 seconds.


In [1]:
# Define a function to calcualte the number of alive neighbor cells

def count_neighbor(world, i, j):
    count = 0
    for m in range(-1, 2):
        for n in range(-1, 2):
            idx_i = i+m
            idx_j = j+n
            if idx_i >= 0 and idx_i < np.shape(world)[0] and idx_j >= 0 and idx_j < np.shape(world)[1]:
                count += world[idx_i, idx_j]
    
    return count-world[i,j]


In [2]:
# The following code will show a text animation instead of an image animation.

import numpy as np
import matplotlib.pyplot as plt
import time

from IPython.display import display, clear_output  # clear_ouptut is used to refresh the print
np.set_printoptions(threshold=np.inf) # Without this line, the array will be truncated.



# 1. Initialize a matrix with random 0's and 1's.
world_current = np.random.randint(0, 2, (30, 30))
world_future = np.random.randint(0, 1, (30, 30))

# 2. Write a for-loop with some iterations.

for c in range(100):

    # Update each cell, based on the rules.
    for i in range(np.shape(world_current)[0]):
        for j in range(np.shape(world_current)[1]):
            
            count = count_neighbor(world_current, i, j)
            if world_current[i, j] == 1 and (count == 2 or count == 3):
                world_future[i, j] = 1
            elif world_current[i, j] == 0 and count == 3:
                world_future[i, j] = 1
            else:
                world_future[i, j] = 0

    world_current, world_future = world_future, world_current # Swaps the variable name of two arrays
    clear_output(wait=True)
    print(world_current)  # use display(f) if you encounter performance issues
    time.sleep(0.25)
    

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0

In [4]:
# This code shows image animation after simulation is finished.

import numpy as np
import matplotlib.pyplot as plt


# Animation in JupyterLab is not intuitive. 
# The following code is to set up the animation.
import matplotlib.animation

plt.rcParams["animation.html"] = "jshtml"
plt.rcParams['figure.dpi'] = 150  
plt.ioff()
fig, ax = plt.subplots()



# 1. Initialize a matrix with random 0's and 1's.
world_current = np.random.randint(0, 2, (30, 30))
world_future = np.random.randint(0, 1, (30, 30))


def animate(t):
    global world_current, world_future # To manipulate the variables outside the function, you need a global keyword.
    
    # Update each cell, based on the rules.
    for i in range(np.shape(world_current)[0]):
        for j in range(np.shape(world_current)[1]):

            count = count_neighbor(world_current, i, j)
            if world_current[i, j] == 1 and (count == 2 or count == 3):
                world_future[i, j] = 1
            elif world_current[i, j] == 0 and count == 3:
                world_future[i, j] = 1
            else:
                world_future[i, j] = 0
    world_current, world_future = world_future, world_current  # Swaps the variable name of two arrays
    plt.cla()
    ax.imshow(world_current)

    
matplotlib.animation.FuncAnimation(fig, animate, frames=100) # Simulates frames and shows an animation panel.
