#### Problem 1 solution

In [88]:
# Complete the following function.

# DO NOT CHANGE THE FUNCTION NAME AND ARGUMENTS!!!

import numpy as np
def n_array(n, m):
    return np.ones(m) * n


In [100]:
n = 7
m = 30
a = n_array(n, m)
a

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

---

#### Problem 2 solution

In [90]:
# Change the following function.

# DO NOT CHANGE THE FUNCTION NAME AND ARGUMENTS!!!

import numpy as np


def test_nonnegative( x ):
    return np.all(x>=0)


In [91]:
# The following code is provided for your test.
# You can modify it as you want, to test your function.

a = np.array([-1, 0, 1])
print(test_nonnegative(a))

b = np.arange(5)
print(test_nonnegative(b))

c = np.arange(-5, 10)
print(test_nonnegative(c))

False
True
False


---

#### Problem 3 solution

In [5]:
# Complete the following function.

# DO NOT CHANGE THE FUNCTION NAME AND ARGUMENTS!!!

import numpy as np
def c2f( c ):
    return (c*9/5)+32
    

In [6]:
c = np.array([-1, 0, 1, 2, 4, 35, 36, 36.5, 37, 38, 99, 100])
f = c2f(c)
list(zip(c,f))

[(-1.0, 30.2),
 (0.0, 32.0),
 (1.0, 33.8),
 (2.0, 35.6),
 (4.0, 39.2),
 (35.0, 95.0),
 (36.0, 96.8),
 (36.5, 97.7),
 (37.0, 98.6),
 (38.0, 100.4),
 (99.0, 210.2),
 (100.0, 212.0)]

---

#### Problem 4 solution

In [94]:
# Complete the following function.

# DO NOT CHANGE THE FUNCTION NAME AND ARGUMENTS!!!

import numpy as np
def get_deviation( x ):
    x_bar = x.sum()/x.size
    D = np.absolute((x-x_bar)).sum()/x.size
    return D

In [103]:
data = np.arange(100)
D = get_deviation(data)
print(D)

data = np.array([5,3,7,9,16,3,9,8,21])
D = get_deviation(data)
print(D)

25.0
4.222222222222222


---

#### Problem 5 solution

In [105]:
# Complete the following function.

# DO NOT CHANGE THE FUNCTION NAME AND ARGUMENTS!!!

import numpy as np
from scipy.special import factorial

def coefficients( n ):
    num = np.ones(n+1)*n
    den = np.arange(n+1)
    
    return factorial(num)/factorial(den)/factorial(n-den)
    

In [99]:
for n in range(10):
    print(coefficients(n))

[1.]
[1. 1.]
[1. 2. 1.]
[1. 3. 3. 1.]
[1. 4. 6. 4. 1.]
[ 1.  5. 10. 10.  5.  1.]
[ 1.  6. 15. 20. 15.  6.  1.]
[ 1.  7. 21. 35. 35. 21.  7.  1.]
[ 1.  8. 28. 56. 70. 56. 28.  8.  1.]
[  1.   9.  36.  84. 126. 126.  84.  36.   9.   1.]


In [1]:
## Hint 1
## An example of using factorial()

import numpy as np
from scipy.special import factorial

k = np.array([1,2,3,4,5])
m = factorial(k)
print(m)


## Hint 2
## Element-wise addition, subtraction, multiplication, and division
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[  1.   2.   6.  24. 120.]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
